require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - './db/schema.rb'
    - './bin/**'
  NewCops: enable

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ModuleFunction:
  Enabled: false
Style/SlicingWithRange:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
