development:
  secret_key_base: 9acf103a597c572c5b576f957d316d93de7bb6a2a392e8ef447e9d4796b90c3776b53431dc292299bffba56d6d9cad4a665a61ebc2c479eafc0920aca9c6c5f6
  secret_jwt_encryption_key: \xB7\x05\x9Az\xC9\a\xCDYe\xEB\xF2T\xEC!m\x1D\x1C\xB5\x8E\xB0 Qb\xD4\xC7\xEB\xD0b\xCC\x89:[
  secret_tokenizer_base: S8wxcfOaIBLS/g==

test:
  secret_key_base: 3992d62e3cc1217b74fd229397003fcf406a9ef3dff5511e6075a1304748c9fbd8b99e5d88580ef7d4953780787634feeaf40d272d8082396f4dd530a17e2ced
  secret_jwt_encryption_key: \xFB\x91\x11\xF6\x8D1d\xE0\xB6\xB6g\x8A\az,\xECL\xEB\x10@2*\xBA\xAE\xC36\xB9\xD9\x17I7V
  secret_tokenizer_base: jkkjsFJDBrgTbw==

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_jwt_encryption_key: <%= ENV["SECRET_JWT_ENCRYPTION_KEY"] %>
  secret_tokenizer_base: <%= ENV["SECRET_TOKENIZER_BASE"] %>
